name: Build and Publish Docker
on: 
  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Docker Tag
        id: set_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          TAG=${TAG%-*}
          echo ::set-output name=tag::$TAG
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Private service warehouse
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY }}
          username: ${{ secrets.PRIVATE_USERNAME }}
          password: ${{ secrets.PRIVATE_PASSWORD }}
      - name: Build and Publish
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/nexus:${{ steps.set_tag.outputs.tag }}
            ${{ secrets.PRIVATE_REGISTRY }}/nexus:${{ steps.set_tag.outputs.tag }}